### ISSUE TITLE
Bugs while trying to dump objects with meliae

### ISSUE THREAD

**Issue by lmacken** [lmacken/pyrasite#12]
I hit these tracebacks while bouncing between a couple of processes over and over.

<pre>
Traceback (most recent call last):
  File "pyrasite/tools/gui.py", line 573, in selection_cb
    self.dump_objects(proc)
  File "pyrasite/tools/gui.py", line 632, in dump_objects
    map(intify, line.split()[1:]))
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py", line 935, in append
    self.set_row(treeiter, row)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py", line 791, in set_row
    raise ValueError('row sequence has the incorrect number of elements')
ValueError: row sequence has the incorrect number of elements

Traceback (most recent call last):
  File "pyrasite/tools/gui.py", line 301, in obj_selection_cb
    addy = model.get_value(treeiter, 0)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py", line 977, in get_value
    return self._decode_value(treeiter, column, value)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py", line 803, in _decode_value
    value = value.decode('UTF-8')
AttributeError: 'NoneType' object has no attribute 'decode'
</pre>

**Comment by lmacken** [comment]
Migrated to the new pyrasite-gui issue tracker: https://github.com/lmacken/pyrasite-gui/issues/2
