### ISSUE TITLE
Automatically poll for new/removed processes

### ISSUE THREAD

**Issue by lmacken** [lmacken/pyrasite#13]
We should occasional look for new or removed python processes and update our sidebar

**Comment by jlew** [comment]
Additionally,

You should handle when a process clicked is no longer active:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyrasite-2.0beta2-py2.7.egg/pyrasite/tools/gui.py", line 567, in selection_cb
    self.generate_description(proc, title)
  File "/usr/lib/python2.7/site-packages/pyrasite-2.0beta2-py2.7.egg/pyrasite/tools/gui.py", line 318, in generate_description
    p = psutil.Process(proc.pid)
  File "/usr/lib/python2.7/site-packages/psutil/**init**.py", line 100, in **init**
    raise NoSuchProcess(pid, None, "no process found with pid %s" % pid)
psutil.error.NoSuchProcess: no process found with pid 6135
