### ISSUE TITLE
pyrasite-memory-viewer: IOError: [Errno 2] File not found: '/tmp/pyrasite-23216-objects.json'

### ISSUE THREAD

**Issue by spaceone** [lmacken/pyrasite#134]
```
# pyrasite-memory-viewer 23216
Traceback (most recent call last):
  File "/usr/local/bin/pyrasite-memory-viewer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pyrasite/tools/memory_viewer.py", line 150, in main
    objects = loader.load(filename)
  File "/usr/lib/python2.7/dist-packages/meliae/loader.py", line 529, in load
    source, cleanup = files.open_file(source)
  File "/usr/lib/python2.7/dist-packages/meliae/files.py", line 32, in open_file
    source = open(filename, 'rb')
IOError: [Errno 2] File not found: '/tmp/pyrasite-23216-objects.json'
```

Afterwards the python process is not running anymore. :-(

**Comment by Fangyh09** [comment]
Same error

**Comment by zhangming8** [comment]
me too

**Comment by zxiong** [comment]
me too

**Comment by yeyuqiu** [comment]
me too

**Comment by qcymkxyc** [comment]
same error with me

**Comment by sorrat** [comment]
Try
```
echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
```
https://pyrasite.readthedocs.io/en/latest/Installing.html#ubuntu
