### ISSUE TITLE
pyrasite-memory-viewer does not work

### ISSUE THREAD

**Issue by mgedmin** [lmacken/pyrasite#31]
I cloned master, easy_install'ed it into ~/py-lib, tried `pyrasite-memory-viewer somepid` and got this:

```
ImportError: No module named urwid
```

After easy_installing urwid I re-ran that command and got

```
Traceback (most recent call last):
  File "/home/mg/bin/pyrasite-memory-viewer", line 9, in <module>
    load_entry_point('pyrasite==2.0beta9', 'console_scripts', 'pyrasite-memory-viewer')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 305, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2245, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1955, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/mg/py-lib/pyrasite-2.0beta9-py2.7.egg/pyrasite/tools/memory_viewer.py", line 34, in <module>
    from pyrasite.inspect import ObjectInspector
ImportError: No module named inspect
```

**Comment by lmacken** [comment]
'git checkout develop' and try again. I'm going to be merging develop into master and releasing 2.0 soon.

**Comment by mgedmin** [comment]
I was going to send you a couple of pull requests to make the pyrasite command-line version easier to use (explain the meaning of the 'filename' argument; make it easier to use payloads shipped with pyrasite without typing out full pathnames).  Would you like those to be based on master, or on the develop branch?

**Comment by lmacken** [comment]
Yes, please hack on the develop branch :)
