### ISSUE TITLE
[Mac OSX]Use the pyrasite always remain on ipc.connect 

### ISSUE THREAD

**Issue by dreampuf** [lmacken/pyrasite#42]
```
(g)dreampuf@HX:~/hub/fortest/hello$ pyrasite-shell 35548
^CTraceback (most recent call last):
  File "/Users/dreampuf/.virtualenvs/g/bin/pyrasite-shell", line 8, in <module>
    load_entry_point('pyrasite==2.0', 'console_scripts', 'pyrasite-shell')()
  File "/Users/dreampuf/.virtualenvs/g/lib/python2.7/site-packages/pyrasite/tools/shell.py", line 30, in shell
    ipc.connect()
  File "/Users/dreampuf/.virtualenvs/g/lib/python2.7/site-packages/pyrasite/ipc.py", line 95, in connect
    self.wait()
  File "/Users/dreampuf/.virtualenvs/g/lib/python2.7/site-packages/pyrasite/ipc.py", line 151, in wait
    (clientsocket, address) = self.server_sock.accept()
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
KeyboardInterrupt
```

Did I need the special code insert the remote process? or other version of gdb (I could not find the version 7.2 on homebrew)

```
(g)dreampuf@HX:~/hub/fortest/hello$ gdb --version
GNU gdb 6.3.50-20050815 (Apple version gdb-1824) (Thu Nov 15 10:42:43 UTC 2012)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin".
```

**Comment by lmacken** [comment]
I've actually never tested pyrasite on OSX, but others have gotten it working.

Does `pyrasite <pid> helloworld.py` work? If so, it may be a bug in the pyrasite.ipc module.

**Comment by lmacken** [comment]
Oh, I think you need to build the latest gdb by hand, as Apple's version doesn't support the features we need: http://pyrasite.readthedocs.org/en/latest/Installing.html#mac-os-x
