### ISSUE TITLE
Have the reverse connection gracefully handle disconnects

### ISSUE THREAD

**Issue by lmacken** [lmacken/pyrasite#51]
There are cases where the pyrasite-shell may get disconnect from the reverse connection thread. We should figure out how to gracefully recover the connection.

**Comment by lmacken** [comment]
Example of disconnect:

```
>>> mpickle = pickle.dumps(marks[1])  

Traceback (most recent call last):  
  File "/home/eastein/venvs/general/bin/pyrasite-shell", line 8, in <module>  
    load_entry_point('pyrasite==2.0', 'console_scripts', 'pyrasite-shell')()  
  File "/home/eastein/venvs/general/lib/python2.6/site-packages/pyrasite/tools/shell.py", line 61, in shell  
    payload = ipc.recv()  
  File "/home/eastein/venvs/general/lib/python2.6/site-packages/pyrasite/ipc.py", line 174, in recv  
    header_data = self.recv_bytes(4)  
  File "/home/eastein/venvs/general/lib/python2.6/site-packages/pyrasite/ipc.py", line 187, in recv_bytes
    chunk = self.sock.recv(n - len(data))
socket.timeout: timed out
```

**Comment by lmacken** [comment]
Then trying to run the shell again yields:

```
Traceback (most recent call last):
  File "/home/eastein/venvs/general/bin/pyrasite-shell", line 8, in <module>
    load_entry_point('pyrasite==2.0', 'console_scripts', 'pyrasite-shell')()
  File "/home/eastein/venvs/general/lib/python2.6/site-packages/pyrasite/tools/shell.py", line 30, in shell
    ipc.connect()
  File "/home/eastein/venvs/general/lib/python2.6/site-packages/pyrasite/ipc.py", line 95, in connect
    self.wait()
  File "/home/eastein/venvs/general/lib/python2.6/site-packages/pyrasite/ipc.py", line 151, in wait
    (clientsocket, address) = self.server_sock.accept()
  File "/usr/lib/python2.6/socket.py", line 195, in accept
    sock, addr = self._sock.accept()
KeyboardInterrupt
```

**Comment by eastein** [comment]
The latter happens when I hit ^C after waiting forever for it to pick up. It never does.

**Comment by eastein** [comment]
I edited injector.py to turn on verbose mode and got this (on the one that I already timed out from once and have since been unable to pyrasite-shell into).

```
(general)eastein@balin ~ :) $ pyrasite-shell 11487
(no debugging symbols found)
Using host libthread_db library "/lib/libthread_db.so.1".
(no debugging symbols found)
(no debugging symbols found)
[Thread debugging using libthread_db enabled]
[New Thread 0xb7c8d8d0 (LWP 11487)]
[New Thread 0xb567eb70 (LWP 11369)]
[New Thread 0xb5e7fb70 (LWP 11363)]
[New Thread 0xb6680b70 (LWP 10602)]
[New Thread 0xb6e81b70 (LWP 10423)]
[New Thread 0xb79d6b70 (LWP 10414)]
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
0xb7f75402 in __kernel_vsyscall ()
[Switching to Thread 0xb7c8d8d0 (LWP 11487)]
$1 = 1
[New Thread 0xb4e7db70 (LWP 12931)]
$2 = 134525008

Cannot get thread event message: debugger service failed
```
