### ISSUE TITLE
NameError: global name 'ipc_timeout' is not defined

### ISSUE THREAD

**Issue by andrewkcarter** [lmacken/pyrasite#67]
When running with `--output localterm`, the `ipc_timeout` variable is undefined. 
```
~/pyrasite-develop# pyrasite --output localterm --ipc-timeout 5 1 dump_stacks.py
Traceback (most recent call last):
  File "/usr/local/bin/pyrasite", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pyrasite/main.py", line 137, in main
    timeout=ipc_timeout)
NameError: global name 'ipc_timeout' is not defined
```

The reference on line 137 needs to be `args.ipc_timeout`, not simply `ipc_timeout`.

**Comment by artms** [comment]
I made pull request for this issue: https://github.com/lmacken/pyrasite/pull/69
